name: main
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  image_picker:
  path_provider:
  convex_bottom_bar:

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/avatars/
    - images/icons/
    - images/logos/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
          weight: 700
        - asset: fonts/Nunito-Bold.ttf
          weight: 500
