const String politicaprivacidade = 'I. Introdução\n'
    'Quando utiliza a RePlate It, confia-\n'
    'nos os seus dados pessoais. Estamos \n'
    'empenhados em manter essa confiança. \n'
    'Para isso, vamos começar por o ajudar a \n'
    'compreender as nossas práticas de \n'
    'privacidade.\n\n'
    'Este aviso descreve os dados pessoais \n'
    '("dados") que recolhemos, como os \n'
    'utilizamos e partilhamos e as suas \n'
    'escolhas relativamente a estes dados. \n'
    'Recomendamos a sua leitura juntamente \n'
    'com a nossa perspetiva geral da \n'
    'privacidade, a qual destaca os pontos \n'
    'principais sobre as nossas práticas de \n'
    'privacidade.\n\n'
    'II. Perspetiva geral\n'
    'A. Âmbito\n'
    'Este aviso aplica-se aos utilizadores dos \n'
    'serviços da RePlate It em qualquer \n'
    'parte do mundo, incluindo utilizadores \n'
    'das aplicações, dos websites e das \n'
    'funcionalidades.\n'
    'Este aviso descreve como a \n'
    'RePlate It e as suas afiliadas \n'
    'recolhem e utilizam dados. Este aviso \n'
    'aplica-se a todos os utilizadores \n'
    'RePlate It em todo o mundo, a \n'
    'menos que utilizem um serviço coberto por um aviso de privacidade diferente.\n'
    'Este aviso também rege as outras recolhas de dados por parte da Uber relacionadas com os seus serviços. \n'
    'Por exemplo, podemos recolher as informações de contacto de proprietários ou colaboradores de restaurantes \n'
    'ou outros comerciantes. Todas as pessoas sujeitas a este aviso são designadas como "utilizadores" neste aviso.\n'
    'As nossas práticas de privacidade estão sujeitas às leis aplicáveis nos locais onde estamos disponíveis. \n'
    'Isto significa que apenas nos envolvemos nas práticas descritas neste aviso num determinado país ou região \n'
    'se as leis desses locais assim o permitirem.\n\n'
    'A RePlate It recolhe dados: \n\n'
    'fornecidos pelos utilizadores à FoodForward, como, por exemplo, durante a criação de uma conta\n'
    'criados durante a utilização dos nossos serviços, como, por exemplo, a localização, a utilização da aplicação e os dados do dispositivo\n'
    'de outras fontes, como outros utilizadores ou proprietários de contas, parceiros de negócios, fornecedores, fornecedores de soluções financeiras e de seguros e autoridades governamentais\n\n'
    'Para sua conveniência, fornecemos um resumo visual dos dados que recolhemos e como os utilizamos aqui.\n\n'
    'A RePlate It recolhe os seguintes dados:\n'
    'fornecidos pelos utilizadores à RePlate It, como, por exemplo, durante a criação de uma conta;\n'
    'criados durante a utilização dos nossos serviços, como, por exemplo, a localização, a utilização da aplicação e os dados do dispositivo;\n'
    'de outras fontes, como outros utilizadores ou proprietários de contas, parceiros de negócios, fornecedores, fornecedores de soluções financeiras e de seguros e autoridades governamentais;\n\n'
    'A RePlate It utiliza os dados para conseguir disponibilizar transportes, entregas e outros produtos e serviços que sejam fiáveis e convenientes. \n'
    'Também utilizamos estes dados:\n\n'
    'para reforçar a segurança e a proteção dos nossos utilizadores e serviços;\n'
    'para o serviço de apoio ao cliente;\n'
    'para investigação e desenvolvimento;\n'
    'para permitir a comunicação entre utilizadores;\n'
    'para fins de marketing e publicidade;\n'
    'para enviar comunicações que não são para fins de marketing aos utilizadores\n'
    'no âmbito de procedimentos legais;\n';

const String sobre =
    'A RePlate It partiu da preocupação com o desperdício de comida diário por parte de inúmeros restaurantes para além da quantidade de pessoas que vivem dificuldades.\n\n'
    'Portugal é o 4º país da UE que mais desperdiça comida. São desperdiçados cerca de 124 quilos por habitante, por ano\n\n.'
    'Juntamente com diversos restaurantes, a RePlate It tomou a iniciativa de melhorar as refeições das pessoas com mais dificuldades e assim, combater a quantidade de comida que já não seria vendida.\n\n'
    'Assim, as pessoas que precisam podem recolher as suas refeições de forma anónima e os restaurantes não irão desperdiçar comida.\n\n';
